keys:
  - &yubikey 67AA5B46E7AF78053167FE343B8F814A784218F8
  - &will age1yggqyza4vmts7uuuuykz42sd8dwqszgcfd6y6avw8ul5pm2ekffsg2gqr2
  - &server age1ylmkgqk0x9e9tg9nv2kelmqu9k5d7hsahvrqr5sywxcexy34g37sdqg5zf

creation_rules:
  - path_regex: secrets/secrets\.yaml$
    key_groups:
      - pgp:
          - *yubikey
        age:
          - *will
          - *server
  - path_regex: (secrets/dnssec|mainnet|signet)/.*
    key_groups:
      - pgp:
          - *yubikey
        age:
          - *will
          - *server
